# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- task: NuGetToolInstaller@1




- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'
    
# .NET Desktop
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: 3.1.401